---
- name: Install MYSQL and other dependencies 
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: present
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb
    - libmysqlclient-dev
       
- name: Update mysql root password 
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ host_domain_env[rmt_host].mysqlpass }}"
    login_user: root
    login_password: "{{ host_domain_env[rmt_host].mysqlpass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

  #- name: Copy the root credentials as .my.cnf file
   # copy: src=/vagrant/root.cnf dest=~/.my.cnf mode=0600
- name: Ensure Anonymous user(s) are not in the database
  mysql_user: name='' host="{{ item }}" login_user=root login_password="{{ host_domain_env[rmt_host].mysqlpass }}" state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ host_domain_env[rmt_host].mysqlpass }}" login_user=root

- name: Display Installed MY SQL version
  command: mysql --version
  register: mysql_version

- name: print mysql version
  debug: 
    var: mysql_version.stdout_lines
