---
- hosts: "localhost"
  tasks:
  
  - pause: 
      seconds: 10
      prompt: "Wait for a min to make sure remote host is ready"

- hosts: "{{ rmt_host }}"
  tasks:
  - name: Include Vars
    include_vars: vars/var.yaml

  - name: This happens on local host to know_host file to avoid man in middle attach error
    local_action:
      module: file
      path: /home/vagrant/.ssh/known_hosts
      state: absent 
    
  - name: Setup | authorized key upload
    authorized_key: 
      user: "{{ host_domain_env[rmt_host].ansible_usr_ssh }}"
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
      path: "/home/vagrant/.ssh/authorized_keys"
      manage_dir: no
    

      #https://www.hashbangcode.com/article/ansible-ssh-setup-playbook
#ansible-playbook -e "ansible_user=vagrant" --ask-vault-pass -bk --extra-vars "rmt_host=jenkins" /vagrant/play_books/ansible_ssh_auto_set_up.yaml
      #$ ansible-playbook -k --extra-vars "rmt_host=jenkins" /vagrant/play_books/ansible_ssh_auto_s